version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: install
          command: apt-get install -y build-essential cmake libssl-dev

      - run:
          name: cmake
          command: cmake ..

      - run:
          name: make
          command: make

