version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: submodules
          command: git submodule update --init --recursive

      - run:
          name: install
          command: apt-get update && apt-get install -y build-essential cmake libssl-dev

      - run:
          name: cmake
          command: cmake -B build.tmp .

      - run:
          name: make
          command: make -C build.tmp

